In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

# Logistic Regression

In [11]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9555555555555556

# SVM

In [13]:
sv = SVC(gamma ='auto')
sv.fit(X_train,y_train)
sv.score(X_test,y_test)

0.4148148148148148

# RandomTree

In [15]:
rt = RandomForestClassifier(n_estimators = 40)
rt.fit(X_train,y_train)
rt.score(X_test,y_test)

0.9629629629629629

# Kfold Cross Validation

In [16]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [19]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 7 8] [5 6]
[0 1 2 3 4 5 6] [7 8]


# Kfold for load_digit

In [20]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [21]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [22]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [25]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [26]:
scores_rf

[0.9348914858096828, 0.9565943238731218, 0.9181969949916527]

# Cross_val 

In [27]:
from sklearn.model_selection import cross_val_score

In [28]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=5)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [30]:
cross_val_score(SVC(gamma='auto'),digits.data, digits.target,cv=5)

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])

In [32]:
cross_val_score(RandomForestClassifier(n_estimators =100),digits.data, digits.target,cv=5)

array([0.925     , 0.90833333, 0.95264624, 0.97214485, 0.92479109])

# Paramter Fine Tuning

In [33]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8759248913718187