In [1]:
from sklearn import svm,datasets
import pandas as pd
ld = datasets.load_iris()

In [2]:
dir(ld)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
df = pd.DataFrame(ld.data,columns = ld.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [4]:
df['flower'] = ld.target
df['flower'] = df['flower'].apply(lambda x:ld.target_names[x])
df[47:150]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
47                 4.6               3.2                1.4               0.2  \
48                 5.3               3.7                1.5               0.2   
49                 5.0               3.3                1.4               0.2   
50                 7.0               3.2                4.7               1.4   
51                 6.4               3.2                4.5               1.5   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

         flower  
47       setosa  
48       setosa  
49       setosa  
50   versicolor  
51   versicolor  
..          ...  
145   virginica  
146   virginica  
147   virginica  
148   virginica  
149   virginica  

[103 rows x 5 columns]

# Use test and train split and manually tune

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(ld.data,ld.target,test_size = 0.3)

In [6]:
model = svm.SVC(kernel='rbf',gamma = 'auto',C=30)
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9555555555555556

# Use cross validation in order to find out

In [10]:
from sklearn.model_selection import cross_val_score

In [20]:
cross_val_score(svm.SVC(kernel = 'linear' ,C=10,gamma = 'auto'),ld.data,ld.target,cv =5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [17]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),ld.data, ld.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [18]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),ld.data, ld.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

Above approach is tiresome and very manual. We can use for loop as an alternative

In [25]:
import numpy as np
kernel = ['rbf','linear']
C = [5,10,20]
score = {}
for k in kernel:
    for c in C:
        scores = cross_val_score(svm.SVC(kernel= k ,C = c,gamma = 'auto'),ld.data,ld.target,cv = 5)
        score[k + '_' + str(c)] = np.average(scores)

score

{'rbf_5': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_5': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

# Approach 3: Use GridSearchCV

In [27]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)
clf.fit(ld.data, ld.target)
clf.cv_results_

{'mean_fit_time': array([0.00314341, 0.        , 0.        , 0.        , 0.0031776 ,
        0.        ]),
 'std_fit_time': array([0.00628681, 0.        , 0.        , 0.        , 0.00635519,
        0.        ]),
 'mean_score_time': array([0.        , 0.00320725, 0.00320759, 0.        , 0.        ,
        0.        ]),
 'std_score_time': array([0.        , 0.0042362 , 0.00641518, 0.        , 0.        ,
        0.        ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [28]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C   
0       0.003143      0.006287         0.000000        0.000000       1  \
1       0.000000      0.000000         0.003207        0.004236       1   
2       0.000000      0.000000         0.003208        0.006415      10   
3       0.000000      0.000000         0.000000        0.000000      10   
4       0.003178      0.006355         0.000000        0.000000      20   
5       0.000000      0.000000         0.000000        0.000000      20   

  param_kernel                         params  split0_test_score   
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667  \
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score   
0                1.0           0.966667           0.966667                1.0  \
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [29]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [30]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [31]:
clf.best_score_

0.9800000000000001

In [33]:
from sklearn.model_selection import RandomizedSearchCV
rf = RandomizedSearchCV(svm.SVC(gamma = 'auto'),{
    'kernel' : ['linear','rbf'],
     'C' : [5,10,20]
},cv = 5,return_train_score = False,n_iter = 2)
rf.fit(ld.data,ld.target)
pd.DataFrame(rf.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1      10          rbf         0.980000

# How about different models with different hyperparameters?

In [36]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [38]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(ld.data, ld.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000       {'n_estimators': 10}
2  logistic_regression    0.966667                   {'C': 5}